In [0]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt


In [0]:
T = 8
D = 2
M = 3

In [0]:
X = np.random.randn(1, T, D)

In [0]:
print(X[0])

[[-0.444321    1.92316628]
 [ 0.83847353  2.42272358]
 [-0.09970431 -0.84727136]
 [ 0.95486693 -0.48437355]
 [-0.41097095 -0.09488751]
 [ 1.07460268  0.7997951 ]
 [ 1.13744447  0.30642805]
 [-1.56991324 -0.10805923]]


In [0]:
def lstm1():
  input_ = Input(shape = (T, D))
  rnn = LSTM(M, return_state = True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  model.summary()
  o, h, c = model.predict(X)
  print("O : ", o)
  print("h: ", h)
  print("c: ", c)

In [0]:
def lstm2():
  input_ = Input(shape = (T, D))
  rnn = LSTM(M, return_state = True, return_sequences = True)
  x = rnn(input_)
  
  model = Model(inputs = input_, outputs = x)
  model.summary()
  o, h, c = model.predict(X)
  print("o is ", o)
  print("h is ", h)
  

In [0]:
def gru1():
  input_ = Input(shape = (T, D))
  rnn = GRU(M, return_state = True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  model.summary()
  o, h = model.predict(X)
  print("o is ", o)
  print("h is ", h)

In [0]:
def gru2():
  input_ = Input(shape = (T, D))
  rnn = GRU(M, return_state = True, return_sequences = True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  model.summary()
  o, h = model.predict(X)
  print("o is ", o)
  print("h is ", h)

In [0]:
lstm1()

Model: "model_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        (None, 8, 2)              0         
_________________________________________________________________
lstm_10 (LSTM)               [(None, 3), (None, 3), (N 72        
Total params: 72
Trainable params: 72
Non-trainable params: 0
_________________________________________________________________
O :  [[-0.0717174  -0.00074366 -0.09987602]]
h:  [[-0.0717174  -0.00074366 -0.09987602]]
c:  [[-0.12307899 -0.001588   -0.18709154]]


In [0]:
lstm2()

Model: "model_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        (None, 8, 2)              0         
_________________________________________________________________
lstm_11 (LSTM)               [(None, 8, 3), (None, 3), 72        
Total params: 72
Trainable params: 72
Non-trainable params: 0
_________________________________________________________________
o is  [[[ 0.10381114 -0.02072762 -0.10384363]
  [ 0.32743493  0.28275782 -0.15813026]
  [ 0.16823985  0.08391283 -0.22336806]
  [ 0.22424085  0.19114533 -0.03862991]
  [ 0.06126262  0.08493593  0.00452233]
  [ 0.26454878  0.28382188 -0.09317151]
  [ 0.33724678  0.35248154 -0.09993012]
  [ 0.0751422   0.10135531 -0.0360619 ]]]
h is  [[ 0.0751422   0.10135531 -0.0360619 ]]


In [0]:
gru1()

Model: "model_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        (None, 8, 2)              0         
_________________________________________________________________
gru_5 (GRU)                  [(None, 3), (None, 3)]    54        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________
o is  [[-0.0133072  -0.07707047 -0.11558366]]
h is  [[-0.0133072  -0.07707047 -0.11558366]]


In [0]:
gru2()

Model: "model_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_17 (InputLayer)        (None, 8, 2)              0         
_________________________________________________________________
gru_6 (GRU)                  [(None, 8, 3), (None, 3)] 54        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________
o is  [[[ 0.10393859  0.2590964   0.02833019]
  [ 0.24354829  0.5863046  -0.00972379]
  [-0.07621565  0.25258026  0.02510591]
  [ 0.2106675   0.16201466 -0.00920346]
  [-0.01082141  0.03913401  0.02884764]
  [ 0.31009665  0.23740226 -0.02741196]
  [ 0.5113947   0.25384378 -0.05057724]
  [-0.06739503 -0.00314978  0.11451485]]]
h is  [[-0.06739503 -0.00314978  0.11451485]]
